# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: exo/networking/grpc/node_service.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'exo/networking/grpc/node_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&exo/networking/grpc/node_service.proto\x12\x13\x65xo.networking.grpc\"S\n\x05Shard\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x13\n\x0bstart_layer\x18\x02 \x01(\x05\x12\x11\n\tend_layer\x18\x03 \x01(\x05\x12\x10\n\x08n_layers\x18\x04 \x01(\x05\"\xad\x01\n\x0eTransferStatus\x12:\n\x06status\x18\x01 \x01(\x0e\x32*.exo.networking.grpc.TransferStatus.Status\x12\x15\n\rerror_message\x18\x02 \x01(\t\x12\x16\n\x0e\x62ytes_received\x18\x03 \x01(\x03\x12\x13\n\x0btotal_bytes\x18\x04 \x01(\x03\"\x1b\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01\"\x83\x02\n\nShardChunk\x12<\n\x08metadata\x18\x01 \x01(\x0b\x32(.exo.networking.grpc.ShardChunk.MetadataH\x00\x12\x14\n\nchunk_data\x18\x02 \x01(\x0cH\x00\x12\x0e\n\x06offset\x18\x03 \x01(\x03\x12\x0f\n\x07is_last\x18\x04 \x01(\x08\x1au\n\x08Metadata\x12)\n\x05shard\x18\x01 \x01(\x0b\x32\x1a.exo.networking.grpc.Shard\x12\x18\n\x10inference_engine\x18\x02 \x01(\t\x12\x11\n\tfile_name\x18\x03 \x01(\t\x12\x11\n\tfile_size\x18\x04 \x01(\x03\x42\t\n\x07\x63ontent\"\x14\n\x12HealthCheckRequest\")\n\x13HealthCheckResponse\x12\x12\n\nis_healthy\x18\x01 \x01(\x08\"7\n\x0bShardStatus\x12\x11\n\thas_shard\x18\x01 \x01(\x08\x12\x15\n\rerror_message\x18\x02 \x01(\t2\x9a\x02\n\x0bNodeService\x12N\n\x0eGetShardStatus\x12\x1a.exo.networking.grpc.Shard\x1a .exo.networking.grpc.ShardStatus\x12Y\n\rTransferShard\x12\x1f.exo.networking.grpc.ShardChunk\x1a#.exo.networking.grpc.TransferStatus(\x01\x30\x01\x12`\n\x0bHealthCheck\x12\'.exo.networking.grpc.HealthCheckRequest\x1a(.exo.networking.grpc.HealthCheckResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exo.networking.grpc.node_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SHARD']._serialized_start=63
  _globals['_SHARD']._serialized_end=146
  _globals['_TRANSFERSTATUS']._serialized_start=149
  _globals['_TRANSFERSTATUS']._serialized_end=322
  _globals['_TRANSFERSTATUS_STATUS']._serialized_start=295
  _globals['_TRANSFERSTATUS_STATUS']._serialized_end=322
  _globals['_SHARDCHUNK']._serialized_start=325
  _globals['_SHARDCHUNK']._serialized_end=584
  _globals['_SHARDCHUNK_METADATA']._serialized_start=456
  _globals['_SHARDCHUNK_METADATA']._serialized_end=573
  _globals['_HEALTHCHECKREQUEST']._serialized_start=586
  _globals['_HEALTHCHECKREQUEST']._serialized_end=606
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=608
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=649
  _globals['_SHARDSTATUS']._serialized_start=651
  _globals['_SHARDSTATUS']._serialized_end=706
  _globals['_NODESERVICE']._serialized_start=709
  _globals['_NODESERVICE']._serialized_end=991
# @@protoc_insertion_point(module_scope)
